version: '3'

services:
  backend:
    build: ./app/backend
    ports:
      - "5000:5000"
      - "8000:8000"
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build: ./app/frontend
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:v2.30.0
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    networks:
      - app-network

  grafana:
    image: grafana/grafana:8.1.2
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  grafana-storage: 